# quartz.config.yaml
configuration:
  pageTitle: "Umberto Calò - Curriculum Vitae"
  enableSPA: true
  enablePopovers: true
  analytics: null
  locale: "it-IT"
  baseUrl: "umbertocalo.dpdns.org"
  ignorePatterns: ["private", "templates", ".obsidian"]
  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: "Schibsted Grotesk"
      body: "Source Sans Pro"
      code: "IBM Plex Mono"
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#4e4e4e"
        dark: "#2b2b2b"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: "rgba(143, 159, 169, 0.15)"

plugins:
  - source: github:quartz-community/created-modified-date
    enabled: true
    order: 10
  - source: github:quartz-community/syntax-highlighting
    enabled: true
    order: 20